name: $(BuildID)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

resources:
  - repo: self
    clean: true

jobs:
  ### Linux build ###
  - job: LINUX
    displayName: Linux
    condition: succeeded()
    pool:
      vmImage: 'ubuntu-latest'
    timeoutInMinutes: 60
    steps:
      - task: UseDotNet@2
        displayName: 'Use .NET 6.0 SDK'
        inputs:
          version: 6.0.x
          performMultiLevelLookup: true
          installationPath: $(Agent.ToolsDirectory)/dotnet
      - task: UseDotNet@2
        displayName: 'Use .NET 5.0 SDK'
        inputs:
          version: 5.0.x
          performMultiLevelLookup: true
          installationPath: $(Agent.ToolsDirectory)/dotnet
      - task: UseDotNet@2
        displayName: 'Use .NET Core 3.1 SDK'
        inputs:
          version: 3.1.x
          performMultiLevelLookup: true
          installationPath: $(Agent.ToolsDirectory)/dotnet
      - task: UseDotNet@2
        displayName: 'Use .NET Core 2.1 SDK'
        inputs:
          version: 2.1.x
          performMultiLevelLookup: true
          installationPath: $(Agent.ToolsDirectory)/dotnet
      - powershell: ./build.ps1 -clean -configuration Release -build -run
        displayName: build and run
        env:
          # Environment variables for IoT hub device samples
          IOTHUB_DEVICE_CONN_STRING: $(IOTHUB-DEVICE-CONN-STRING)
          IOTHUB_MODULE_CONN_STRING: $(IOTHUB-MODULE-CONN-STRING)
          PNP_TC_DEVICE_CONN_STRING: $(PNP-TC-DEVICE-CONN-STRING)
          PNP_THERMOSTAT_DEVICE_CONN_STRING: $(PNP-THERMOSTAT-DEVICE-CONN-STRING)

          # Environment variables for IoT hub service samples
          IOTHUB_CONNECTION_STRING: $(IOTHUB-CONNECTION-STRING)
          IOTHUB_X509_DEVICE_PFX_THUMBPRINT: $(IOTHUB-X509-DEVICE-PFX-THUMBPRINT)
          STORAGE_ACCOUNT_CONNECTION_STRING: $(STORAGE-ACCOUNT-CONNECTION-STRING)
          FAR_AWAY_IOTHUB_CONNECTION_STRING: $(FAR-AWAY-IOTHUB-CONNECTION-STRING)
          MSFT_TENANT_ID: $(MSFT-TENANT-ID)
          E2E_TEST_AAD_APP_CLIENT_ID: $(E2E-TEST-AAD-APP-CLIENT-ID)
          E2E_TEST_AAD_APP_CLIENT_SECRET: $(E2E-TEST-AAD-APP-CLIENT-SECRET)
          IOT_HUB_SAS_KEY: $(IOTHUB-SAS-KEY)
          IOT_HUB_SAS_KEY_NAME: $(IOTHUB-SAS-KEY-NAME)

          # PATH-TO-DEVICE-PREFIX-FOR-DELETION-FILE is a variable configured on the pipeline. The possible values are: csharp_devices_list.csv, csharp_samples_devices_list.csv.
          # The value of this variable determines whether to delete devices created by the sample or e2e tests.
          # csharp_devices_list.csv contains the prefixes of devices created by e2e tests.
          # csharp_samples_devices_list.csv contains the prefixes of devices created by samples.
          PATH_TO_DEVICE_PREFIX_FOR_DELETION_FILE: $(PATH-TO-DEVICE-PREFIX-FOR-DELETION-FILE)

          # Environment variables for DPS device samples
          DPS_IDSCOPE: $(DPS-IDSCOPE)
          DPS_SYMMETRIC_KEY_INDIVIDUAL_ENROLLMENT_REGISTRATION_ID : $(DPS-SYMMETRIC-KEY-INDIVIDUAL-ENROLLMENT-REGISTRATION-ID)
          DPS_SYMMETRIC_KEY_INDIVIDUAL_ENROLLEMNT_PRIMARY_KEY : $(DPS-SYMMETRIC-KEY-INDIVIDUAL-ENROLLEMNT-PRIMARY-KEY)

          # Environment variables for DPS service samples
          PROVISIONING_CONNECTION_STRING: $(PROVISIONING-CONNECTION-STRING)

    ### Windows build ###
  - job: WINDOWS
    displayName: Windows
    # Since the samples run against the same Azure resources, CRUD operations will fight for the same resources.
    # So, the builds have been serialized. Comment out the line below to run them in parallel.
    dependsOn: LINUX
    condition: succeeded()
    pool:
      vmImage: 'windows-latest'
    timeoutInMinutes: 60
    steps:
      - task: UseDotNet@2
        displayName: 'Use .NET 6.0 SDK'
        inputs:
          version: 6.0.x
          performMultiLevelLookup: true
          installationPath: $(Agent.ToolsDirectory)/dotnet
      - task: UseDotNet@2
        displayName: 'Use .NET 5.0 SDK'
        inputs:
          version: 5.0.x
          performMultiLevelLookup: true
          installationPath: $(Agent.ToolsDirectory)/dotnet
      - task: UseDotNet@2
        displayName: 'Use .NET Core 3.1 SDK'
        inputs:
          version: 3.1.x
          performMultiLevelLookup: true
          installationPath: $(Agent.ToolsDirectory)/dotnet
      - task: UseDotNet@2
        displayName: 'Use .NET Core 2.1 SDK'
        inputs:
          version: 2.1.x
          performMultiLevelLookup: true
          installationPath: $(Agent.ToolsDirectory)/dotnet
      - powershell: ./build.ps1 -clean -configuration Release -run
        displayName: build and run
        env:
          # Environment variables for IoT hub device samples
          IOTHUB_DEVICE_CONN_STRING: $(IOTHUB-DEVICE-CONN-STRING)
          IOTHUB_MODULE_CONN_STRING: $(IOTHUB-MODULE-CONN-STRING)
          PNP_TC_DEVICE_CONN_STRING: $(PNP-TC-DEVICE-CONN-STRING)
          PNP_THERMOSTAT_DEVICE_CONN_STRING: $(PNP-THERMOSTAT-DEVICE-CONN-STRING)

          # Environment variables for IoT hub service samples
          IOTHUB_CONNECTION_STRING: $(IOTHUB-CONNECTION-STRING)
          IOTHUB_X509_DEVICE_PFX_THUMBPRINT: $(IOTHUB-X509-DEVICE-PFX-THUMBPRINT)
          STORAGE_ACCOUNT_CONNECTION_STRING: $(STORAGE-ACCOUNT-CONNECTION-STRING)
          FAR_AWAY_IOTHUB_CONNECTION_STRING: $(FAR-AWAY-IOTHUB-CONNECTION-STRING)
          MSFT_TENANT_ID: $(MSFT-TENANT-ID)
          E2E_TEST_AAD_APP_CLIENT_ID: $(E2E-TEST-AAD-APP-CLIENT-ID)
          E2E_TEST_AAD_APP_CLIENT_SECRET: $(E2E-TEST-AAD-APP-CLIENT-SECRET)
          IOT_HUB_SAS_KEY: $(IOTHUB-SAS-KEY)
          IOT_HUB_SAS_KEY_NAME: $(IOTHUB-SAS-KEY-NAME)

          # PATH-TO-DEVICE-PREFIX-FOR-DELETION-FILE is a variable configured on the pipeline. The possible values are: csharp_devices_list.csv, csharp_samples_devices_list.csv.
          # The value of this variable determines whether to delete devices created by the sample or e2e tests.
          # csharp_devices_list.csv contains the prefixes of devices created by e2e tests.
          # csharp_samples_devices_list.csv contains the prefixes of devices created by samples.
          PATH_TO_DEVICE_PREFIX_FOR_DELETION_FILE: $(PATH-TO-DEVICE-PREFIX-FOR-DELETION-FILE)

          # Environment variables for DPS device samples
          DPS_IDSCOPE: $(DPS-IDSCOPE)
          DPS_SYMMETRIC_KEY_INDIVIDUAL_ENROLLMENT_REGISTRATION_ID : $(DPS-SYMMETRIC-KEY-INDIVIDUAL-ENROLLMENT-REGISTRATION-ID)
          DPS_SYMMETRIC_KEY_INDIVIDUAL_ENROLLEMNT_PRIMARY_KEY : $(DPS-SYMMETRIC-KEY-INDIVIDUAL-ENROLLEMNT-PRIMARY-KEY)

          # Environment variables for DPS service samples
          PROVISIONING_CONNECTION_STRING: $(PROVISIONING-CONNECTION-STRING)
