blank_issues_enabled: false 
contact_links: 
  - name: Azure IoT support and help options 
    url: https://docs.microsoft.com/en-us/azure/iot-fundamentals/iot-support-help 
    about: The main landing page for all Azure IoT support options. 
