// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System;
using System.Text.Json.Serialization;

namespace Microsoft.Azure.Devices
{
    /// <summary>
    /// Contains properties of an individual feedback record.
    /// </summary>
    /// <remarks>
    /// Feedback messages are delivery acknowledgments for messages sent to a device from IoT hub.
    /// </remarks>
    public class FeedbackRecord
    {
        /// <summary>
        /// The Id of the cloud-to-device message to which this feedback message relates.
        /// </summary>
        /// <remarks>
        /// Feedback messages are delivery acknowledgments for messages sent to a device from IoT hub.
        /// </remarks>
        [JsonPropertyName("originalMessageId")]
        public string OriginalMessageId { get; internal set; }

        /// <summary>
        /// The device generation Id of the target device of the cloud-to-device message to which this piece of feedback relates.
        /// </summary>
        /// <remarks>
        /// DeviceGenerationId is an IoT hub generated, case-sensitive string. This value is used to distinguish devices with the
        /// same device Id when they have been deleted and re-created.
        /// </remarks>
        [JsonPropertyName("deviceGenerationId")]
        public string DeviceGenerationId { get; internal set; }

        /// <summary>
        /// The Id of the target device of the cloud-to-device message to which this piece of feedback relates.
        /// </summary>
        [JsonPropertyName("deviceId")]
        public string DeviceId { get; internal set; }

        /// <summary>
        /// Date and time that indicates when the outcome of the message happened in UTC (for example, the hub received the feedback message or the original message expired).
        /// </summary>
        [JsonPropertyName("enqueuedTimeUtc")]
        public DateTimeOffset EnqueuedOnUtc { get; internal set; }

        /// <summary>
        /// The status of feedback messages that are generated by the IoT hub.
        /// </summary>
        [JsonPropertyName("statusCode")]
        public FeedbackStatusCode StatusCode { get; internal set; }

        /// <summary>
        /// Description for <see cref="StatusCode"/>.
        /// </summary>
        [JsonPropertyName("description")]
        public string Description { get; internal set; }
    }
}
