@startuml csharpDeviceClientSDKArchitecture
class IotHubBaseClient
{
  + PipelineContext PipelineContext
  + IDelegatingHandler InnerHandler
}

class DeviceClient 
{ 
}

class ModuleClient 
{
}

IotHubBaseClient --* DeviceClient
IotHubBaseClient --* ModuleClient
IotHubBaseClient -> "Transport Pipeline"

package "Transport Pipeline" 
{
  interface IDelegatingHandler 
  {
    ..Transport State..
    + OpenAsync
    + CloseAsync
    + WaitForTransportClosedAsync
    + IsUsable
    ..Device to Cloud (D2C)..
    + SendTelemetryAsync
    ..Cloud to Device (C2D)..
    + EnableReceiveMessageAsync
    + DisableReceiveMessageAsync
    ..Methods..
    + EnableMethodsAsync
    + DisableMethodsAsync
    + SendMethodResponseAsync
    ..Twin..
    + GetTwinAsync
    + UpdateReportedPropertiesAsync
    + EnableTwinPatchAsync
    + DisableTwinPatchAsync
    ..HTTP operations..
    + GetFileUploadSasUriAsync
    + CompleteFileUploadAsync
    + InvokeMethodAsync
  }

  class DefaultDelegatingHandler 
  {
  }

  class ConnectionStateDelegatingHandler
  {
  }

  class RetryDelegatingHandler 
  {
  }

  class ExceptionRemappingHandler
  {
  }

  class TransportDelegatingHandler
  {
    + CreateNewTransportIfNotReady
    + WaitForTransportClosedAsync
  }

  abstract class TransportHandlerBase
  {
    + OnTransportClosedGracefully
    + OnTransportDisconnected
  }

  class AmqpTransportHandler 
  {
  }

  class MqttTransportHandler 
  {
  }

  class HttpTransportHandler 
  {
  }

  IDelegatingHandler <|-- DefaultDelegatingHandler
  DefaultDelegatingHandler <|-- ConnectionStateDelegatingHandler
  DefaultDelegatingHandler <|-- RetryDelegatingHandler
  DefaultDelegatingHandler <|-- ExceptionRemappingHandler
  DefaultDelegatingHandler <|-- TransportDelegatingHandler
  DefaultDelegatingHandler <|-- TransportHandlerBase
  TransportHandlerBase <|-- MqttTransportHandler
  TransportHandlerBase <|-- AmqpTransportHandler
  TransportHandlerBase <|-- HttpTransportHandler
  DefaultDelegatingHandler --> ConnectionStateDelegatingHandler
  ConnectionStateDelegatingHandler -> RetryDelegatingHandler
  RetryDelegatingHandler -> ExceptionRemappingHandler
  ExceptionRemappingHandler-> TransportDelegatingHandler
  TransportDelegatingHandler -> TransportHandlerBase
  TransportHandlerBase -> HttpTransportHandler
}
@enduml