name: $(BuildID)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

jobs:
  - job: WINDOWS
    displayName: Windows
    pool:
      vmImage: windows-2022
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: '.\build.ps1 -runCleanupSamples'
        env:
          IOTHUB_CONNECTION_STRING: $(IOTHUB-CONNECTION-STRING)
          PROVISIONING_CONNECTION_STRING: $(PROVISIONING-CONNECTION-STRING)
          STORAGE_ACCOUNT_CONNECTION_STRING: $(STORAGE-ACCOUNT-CONNECTION-STRING)