name: $(BuildID)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

# https://docs.microsoft.com/azure/devops/pipelines/process/runtime-parameters
parameters:
- name: maxParallelJobs
  displayName: Maximum jobs to run in parallel. Change maxParallel to 1 make OS builds run in serial rather than in parallel.
  type: number
  # Reasonable target to avoid throttling and contention with several PRs running.
  default: 4
- name: jobTimeoutInMinutes
  displayName: Timeout for each job
  type: number
  default: 150
- name: testTargets
  displayName: The .NET test targets to build and run. 'all' and 'min-matrix' (net8.0) are aggregates of the remaining values.
  type: string
  values:
    - default
    - all
    - min-matrix
    - net8.0
    - net4.7.2
  default: default

variables:
# Variables for the buid/test matrix based on the 'testTargets' that turn on/off various test targets specifically or based on the 2 aggregates.
  ${{ if and(eq(parameters['testTargets'], 'default'), eq(variables['Build.Reason'], 'PullRequest')) }}:
    allTestTargets: 'False'
    minMatrix: 'True'
  ${{ elseif eq(parameters['testTargets'], 'default') }}:
    allTestTargets: 'True'
    minMatrix: 'True'
  ${{ else }}:
    allTestTargets: ${{ contains(parameters['testTargets'], 'all') }}
    # We wish to run the minimum test matrix targets if 1) directly specified, 2) if all targets was chosen.
    minMatrix: ${{ or(eq(parameters['testTargets'], 'min-matrix'), eq(variables['allTestTargets'], 'True')) }}

# The remaining build/test targets.
  testNet80: ${{ or(eq(variables['allTestTargets'], 'True'), contains(parameters['testTargets'], 'net8.0')) }}
  testNet472: ${{ or(eq(variables['allTestTargets'], 'True'), contains(parameters['testTargets'], 'net4.7.2')) }}

trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude:
    - docs/*
    - tools/CaptureLogs/*
    - iothub/device/devdoc/*
    - iothub/service/devdoc/*

resources:
  - repo: self
    clean: true

jobs:
  - job: DeployCloudTestResources
    pool:
      vmImage: windows-2022
    steps:     
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'iot hub sdk service connection'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        pwsh: true
        inlineScript: |
          $jsonContent = az account show | ConvertFrom-Json
          $subscriptionId = $jsonContent.Id
          $(Build.SourcesDirectory)/e2e/test/prerequisites/E2ETestsSetup/e2eTestsSetup.ps1 -SubscriptionId $subscriptionId -Region westcentralus -ResourceGroup netsdkgate -GroupCertificatePassword someCertPass -InstallDependencies -GenerateResourcesForTestDevOpsPipeline
            

  ### Linux build ###
  - job: LINUX
    displayName: Linux
    dependsOn: DeployCloudTestResources
    condition: succeeded()
    timeoutInMinutes: ${{ parameters.jobTimeoutInMinutes }}
    variables:
      iotHubConnectionString: $[ dependencies.A.outputs['setvarStep.iotHubConnectionString'] ]  
      dpsConnectionString: $[ dependencies.A.outputs['setvarStep.dpsConnectionString'] ]  
      dpsIdScope: $[ dependencies.A.outputs['setvarStep.dpsIdScope'] ]
    strategy:
      maxParallel: ${{ parameters.maxParallelJobs }}
      matrix:
        .NET 8.0:
          FRAMEWORK: net8.0
          SHOULD_RUN: ${{ eq(variables['testNet80'], 'True') }}
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: PowerShell@2
        displayName: 'Print vars'
        inputs:
          targetType: inline
          script: |
            Write-Host "Build.Reason: ${{ variables['Build.Reason'] }}"
            Write-Host "jobTimeoutInMinutes: ${{ parameters.jobTimeoutInMinutes }}"
            Write-Host "maxParallelJobs: ${{ parameters.maxParallelJobs }}"
            Write-Host "minMatrix: ${{ variables.minMatrix }}"
            Write-Host "testNet60: ${{ variables.testNet60 }}"
            Write-Host "testNet80: ${{ variables.testNet80 }}"
            Write-Host "testNetcore31: ${{ variables.testNetcore31 }}"
            Write-Host "testNetcore21: ${{ variables.testNetcore21 }}"
            Write-Host "testNet472: ${{ variables.testNet472 }}"

      # https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/dotnet-core-tool-installer?view=azure-devops

      # Linux requires .NET 8.0 install for tests to run, no matter which framework target is being tested
      - task: UseDotNet@2
        displayName: 'Use .NET SDK 8.0'
        inputs:
         packageType: sdk
         version: 8.x
         performMultiLevelLookup: true
         installationPath: $(Agent.ToolsDirectory)/dotnet

      - task: PowerShell@2
        displayName: 'build and run unit tests'
        condition: eq(variables.SHOULD_RUN, 'True')
        inputs:
          targetType: inline
          script: |
            dotnet test
        env:
          # Environment variables for IoT Hub E2E tests
          IOTHUB_CONNECTION_STRING: $(iotHubConnectionString)
          #IOTHUB_DEVICE_CONN_STRING: $(IOTHUB-DEVICE-CONN-STRING)
          #IOTHUB_X509_DEVICE_PFX_CERTIFICATE: $(IOTHUB-X509-DEVICE-PFX-CERTIFICATE)
          #IOTHUB_X509_DEVICE_PFX_THUMBPRINT: $(IOTHUB-X509-DEVICE-PFX-THUMBPRINT)

          #IOTHUB_X509_CHAIN_DEVICE_NAME: $(IOTHUB-X509-CHAIN-DEVICE-NAME)
          #IOTHUB_X509_CHAIN_DEVICE_PFX_CERTIFICATE: $(IOTHUB-X509-CHAIN-DEVICE-PFX-CERTIFICATE)
          #IOTHUB_USER_ASSIGNED_MSI_RESOURCE_ID: $(IOTHUB-USER-ASSIGNED-MSI-RESOURCE-ID)
          #IOT_HUB_SAS_KEY: $(IOTHUB-SAS-KEY)
          #IOT_HUB_SAS_KEY_NAME: $(IOTHUB-SAS-KEY-NAME)

          # Environment variables for DPS E2E tests
          DPS_IDSCOPE: $(dpsIdScope)
          PROVISIONING_CONNECTION_STRING: $(dpsConnectionString)
          DPS_GLOBALDEVICEENDPOINT: global.azure-devices-provisioning.net
          #DPS_X509_PFX_CERTIFICATE_PASSWORD: $(DPS-X509-PFX-CERTIFICATE-PASSWORD)
          #DPS_X509_GROUP_ENROLLMENT_NAME: $(DPS-X509-GROUP-ENROLLMENT-NAME)

          # Environment variables for Azure resources used for E2E tests (common)
          #X509_CHAIN_ROOT_CA_CERTIFICATE: $(X509-CHAIN-ROOT-CA-CERTIFICATE)
          #X509_CHAIN_INTERMEDIATE1_CERTIFICATE: $(X509-CHAIN-INTERMEDIATE1-CERTIFICATE)
          #X509_CHAIN_INTERMEDIATE2_CERTIFICATE: $(X509-CHAIN-INTERMEDIATE2-CERTIFICATE)
          #X509_CHAIN_INTERMEDIATE2_PFX_CERTIFICATE: $(X509-CHAIN-INTERMEDIATE2-PFX-CERTIFICATE)
          #STORAGE_ACCOUNT_CONNECTION_STRING: $(STORAGE-ACCOUNT-CONNECTION-STRING)
          #MSFT_TENANT_ID: $(MSFT-TENANT-ID)
          #E2E_TEST_AAD_APP_CLIENT_ID: $(E2E-TEST-AAD-APP-CLIENT-ID)
          #E2E_TEST_AAD_APP_CLIENT_SECRET: $(E2E-TEST-AAD-APP-CLIENT-SECRET)
          #E2E_IKEY: $(E2E-IKEY)

          # Environment variables for the DevOps pipeline
          #PROXY_SERVER_ADDRESS: 127.0.0.1:8888
          TARGET_BRANCH: $(System.PullRequest.TargetBranch)
          FRAMEWORK: $(FRAMEWORK)

          # Environment variables for invalid certificate tests
          #IOTHUB_DEVICE_CONN_STRING_INVALIDCERT: $(IOTHUB-DEVICE-CONN-STRING-INVALIDCERT)
          #IOTHUB_CONN_STRING_INVALIDCERT: $(IOTHUB-CONN-STRING-INVALIDCERT)
          #DPS_GLOBALDEVICEENDPOINT_INVALIDCERT: $(DPS-GLOBALDEVICEENDPOINT-INVALIDCERT)
          #PROVISIONING_CONNECTION_STRING_INVALIDCERT: $(PROVISIONING-CONNECTION-STRING-INVALIDCERT)

          # Environment variables used by Log Analytics Workspace for Azure Security Center
          #LA_AAD_APP_ID: $(LA-AAD-APP-ID)
          #LA_AAD_APP_CERT_BASE64: $(LA-AAD-APP-CERT-BASE64)
          #LA_WORKSPACE_ID: $(LA-WORKSPACE-ID)

          # Environment variable for running samples/cleanups
          #PATH_TO_DEVICE_PREFIX_FOR_DELETION_FILE: $(PATH-TO-DEVICE-PREFIX-FOR-DELETION-FILE)
          #PNP_TC_DEVICE_CONN_STRING: $(PNP-TC-DEVICE-CONN-STRING)
          #PNP_THERMOSTAT_DEVICE_CONN_STRING: $(PNP-THERMOSTAT-DEVICE-CONN-STRING)
          #DPS_SYMMETRIC_KEY_INDIVIDUAL_ENROLLMENT_REGISTRATION_ID: $(DPS-SYMMETRIC-KEY-INDIVIDUAL-ENROLLMENT-REGISTRATION-ID)
          #DPS_SYMMETRIC_KEY_INDIVIDUAL_ENROLLEMNT_PRIMARY_KEY: $(DPS-SYMMETRIC-KEY-INDIVIDUAL-ENROLLEMNT-PRIMARY-KEY)
            

      - task: PublishTestResults@2
        displayName: "Publish Test Results **/*.trx"
        condition: eq(variables.SHOULD_RUN, 'True')
        inputs:
          testRunner: VSTest
          testRunTitle: "Linux Tests ($(FRAMEWORK)) (Attempt $(System.JobAttempt))"
          testResultsFiles: "**/*.trx"

      - task: CopyFiles@2
        displayName: "Copy files to the artifacts folder"
        condition: eq(variables.SHOULD_RUN, 'True')
        inputs:
          SourceFolder: "$(Build.SourcesDirectory)"
          Contents: "**/*.trx"
          TargetFolder: "$(Build.ArtifactStagingDirectory)"

      - task: PublishBuildArtifacts@1
        displayName: "Publish Artifact: testresults_linux_$(FRAMEWORK)"
        condition: eq(variables.SHOULD_RUN, 'True')
        inputs:
          ArtifactName: testresults_linux_$(FRAMEWORK)
        
      - task: ComponentGovernanceComponentDetection@0
        displayName: Component Governance Detection
        condition: eq(variables.SHOULD_RUN, 'True')
        inputs:
          scanType: 'Register'
          verbosity: 'Verbose'
          alertWarningLevel: 'Low' # The task will present a warning, but will not cause the build to fail

 ### Windows build ###
  - job: WINDOWS
    dependsOn: DeployCloudTestResources
    displayName: Windows
    condition: succeeded()
    timeoutInMinutes: ${{ parameters.jobTimeoutInMinutes }}
    strategy:
      maxParallel: ${{ parameters.maxParallelJobs }}
      matrix:
        .NET 8.0:
          FRAMEWORK: net8.0
          SHOULD_RUN: ${{ eq(variables['testNet80'], 'True') }}
        .NET 4.7.2:
          FRAMEWORK: net472
          SHOULD_RUN: ${{ eq(variables['testNet472'], 'True') }}
    pool:
      vmImage: windows-2022
    steps:
      - task: PowerShell@2
        displayName: 'Print vars'
        condition: eq(variables.SHOULD_RUN, 'True')
        inputs:
          targetType: inline
          script: |
            Write-Host "Build.Reason: ${{ variables['Build.Reason'] }}"
            Write-Host "jobTimeoutInMinutes: ${{ parameters.jobTimeoutInMinutes }}"
            Write-Host "maxParallelJobs: ${{ parameters.maxParallelJobs }}"
            Write-Host "minMatrix: ${{ variables.minMatrix }}"
            Write-Host "testNet60: ${{ variables.testNet60 }}"
            Write-Host "testNet80: ${{ variables.testNet80 }}"
            Write-Host "testNetcore31: ${{ variables.testNetcore31 }}"
            Write-Host "testNetcore21: ${{ variables.testNetcore21 }}"
            Write-Host "testNet472: ${{ variables.testNet472 }}"

      - ${{ if eq(variables['testNet80'], 'True') }}:
        - task: UseDotNet@2
          displayName: 'Use .NET SDK 8.0'
          inputs:
            packageType: sdk
            version: 8.x
            performMultiLevelLookup: true
            installationPath: $(Agent.ToolsDirectory)/dotnet

      - ${{ if eq(variables['testNet472'], 'True') }}:
        - task: CmdLine@2
          displayName: 'Install .NET 4.7.2'
          inputs:
            script: 'choco install -y netfx-4.7.2-devpack'

      - task: PowerShell@2
        displayName: 'build and run unit tests'
        condition: eq(variables.SHOULD_RUN, 'True')
        inputs:
          targetType: inline
          script: |
            dotnet test --filter TestCategory=Unit
      - task: PublishTestResults@2
        displayName: "Publish Test Results **/*.trx"
        inputs:
          testRunner: VSTest
          testResultsFiles: "**/*.trx"
          testRunTitle: "Windows Tests ($(FRAMEWORK)) (Attempt $(System.JobAttempt))"
          platform: Windows
          configuration: "Debug UT + Release E2E ($(FRAMEWORK))"
        condition: eq(variables.SHOULD_RUN, 'True')
        
      - task: ComponentGovernanceComponentDetection@0
        displayName: Component Governance Detection
        condition: eq(variables.SHOULD_RUN, 'True')
        inputs:
          scanType: 'Register'
          verbosity: 'Verbose'
          alertWarningLevel: 'Low' # The task will present a warning, but will not cause the build to fail

  ### .Net SDL Analyzers ###
  - job: DOTNet_SDL_Analyzers
    displayName: .Net SDL Analyzers
    timeoutInMinutes: 60

    condition: succeeded()
    pool:
      vmImage: windows-2022
    steps:
      - powershell: .\build.ps1 -clean -build -configutaion Debug -package
        displayName: Build Package

      - task: ComponentGovernanceComponentDetection@0
        displayName: "Component Detection"
      
      - task: securedevelopmentteam.vss-secure-development-tools.build-task-policheck.PoliCheck@2
        displayName: "Run PoliCheck"
        inputs:
          targetType: F
          optionsRulesDBPath: '$(Build.SourcesDirectory)\vsts\PolicheckExclusionsDB.mdb'
          optionsSEV: '1|2|3|4'
          optionsPE: 1
      
      - task: securedevelopmentteam.vss-secure-development-tools.build-task-antimalware.AntiMalware@4
        displayName: "Run MpCmdRun.exe"
        inputs:
          EnableServices: true
          SignatureFreshness: OneDay
          # Signature refreshes on Hosted Agents can sometimes have a delay of a day or two.
          # The support team already has a process to address this, so our pipeline can treat stale signatures as warnings (instead of treating it as an error).
          TreatStaleSignatureAs: Warning

      - task: securedevelopmentteam.vss-secure-development-tools.build-task-binskim.BinSkim@3
        displayName: "Run BinSkim"
        inputs:
          arguments: 'analyze  $(Build.SourcesDirectory)\Microsoft.Azure.Devices.*.dll --recurse --verbose'

        # TODO #181 Config issue: must run on Debug builds only with valid PDBs.
        enabled: false

      - task: securedevelopmentteam.vss-secure-development-tools.build-task-codemetrics.CodeMetrics@1
        displayName: "Run CodeMetrics"
        inputs:
          Files: '$(Build.SourcesDirectory)\**\Microsoft.Azure.Devices.*.dll'

        # TODO #181 Config issue: must run on Debug builds only with valid PDBs.
        enabled: false

      - task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@3
        displayName: "Run CredScan"
        inputs:
          toolMajorVersion: V2
          suppressionsFile: vsts/CredScanSuppressions.json
          regexMatchTimeoutInSeconds: 5

          # TODO #181 Samples / tests fail the test due to fake connection strings.
          debugMode: false

      - task: securedevelopmentteam.vss-secure-development-tools.build-task-publishsecurityanalysislogs.PublishSecurityAnalysisLogs@3
        displayName: "Publish Security Analysis Logs"

      - task: securedevelopmentteam.vss-secure-development-tools.build-task-report.SdtReport@2
        displayName: "Create Security Analysis Report"
        inputs:
          AllTools: true
          
      - task: ComponentGovernanceComponentDetection@0
        displayName: Component Governance Detection
        inputs:
          scanType: 'Register'
          verbosity: 'Verbose'
          alertWarningLevel: 'Low' # The task will present a warning, but will not cause the build to fail
        condition: always()

      - task: securedevelopmentteam.vss-secure-development-tools.build-task-uploadtotsa.TSAUpload@2
        displayName: 'TSA upload'
        inputs:
          GdnPublishTsaOnboard: false
          GdnPublishTsaConfigFile: '$(Build.SourcesDirectory)/vsts/TsaUploadConfigFile.json'
          GdnPublishTsaExportedResultsPublishable: true

      - task: securedevelopmentteam.vss-secure-development-tools.build-task-postanalysis.PostAnalysis@1
        displayName: "Post Analysis"
        inputs:
          AllTools: true

        # TODO #181 Enable post analysis to break builds after all above items are enabled.
        enabled: false

# END: SDL and Compliance tasks #

  - job: TearDownCloudTestResources
    condition: always()
    dependsOn:
      - WINDOWS
      - LINUX
      - DeployCloudTestResources
    pool:
      vmImage: windows-2022
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'iot hub sdk service connection'
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az group delete --name netsdkgate --y
          # don't forget to delete RBAC resources as well
